### ISSUE TITLE
condition always true: potential bug

### ISSUE THREAD

**Issue by navid-kalaei** [miningmeter/stratum-proxy#6]
In create/update user API, the [user will not be nil](https://github.com/miningmeter/stratum-proxy/blob/bdbee746836f369836876ecbade8b507f251d412/api.go#L47) ever since it has been allocated in memory [lines before](https://github.com/miningmeter/stratum-proxy/blob/bdbee746836f369836876ecbade8b507f251d412/api.go#L44)

**Comment by PikaYellow35** [comment]
Thanks for a bug. I'm fixed it in nearest time.
